/* automatically generated by rust-bindgen 0.59.2 */

extern "C" {
    pub fn demu_i2c(
        mem: *mut ::std::os::raw::c_ulonglong,
        desc: *mut ::std::os::raw::c_ulonglong,
        used: *mut ::std::os::raw::c_ulonglong,
        avail: *mut ::std::os::raw::c_ulonglong,
        fd: *mut ::std::os::raw::c_ulonglong,
        call: ::std::os::raw::c_int,
        kick: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;

    pub fn call_guest();
}
